2019-11-06 14:58:27,819 ERROR: Exception on /reset_password_request [GET] [in /Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/routes.py", line 162, in reset_password_request
    title='Reset Password', form=form)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/templates/reset_password_request.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2019-11-06 14:59:55,728 INFO: BusSim startup [in /Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/__init__.py:50]
2019-11-06 15:00:37,728 INFO: BusSim startup [in /Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/__init__.py:50]
2019-11-06 15:09:01,316 INFO: BusSim startup [in /Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/__init__.py:50]
2019-11-06 15:09:29,075 ERROR: Exception on /reset_password_request [GET] [in /Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/routes.py", line 162, in reset_password_request
    title='Reset Password', user=user, form=form)
UnboundLocalError: local variable 'user' referenced before assignment
2019-11-06 15:21:54,559 INFO: BusSim startup [in /Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/__init__.py:50]
2019-11-06 15:22:06,589 ERROR: Exception on /reset_password_request [GET] [in /Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/routes.py", line 162, in reset_password_request
    title='Reset Password', user=user, form=form)
UnboundLocalError: local variable 'user' referenced before assignment
2019-11-06 15:22:36,136 INFO: BusSim startup [in /Users/tm/GoogleDrive/tm/Projects/2_active/BusSim/Website/app/__init__.py:50]
